code_review:
  disable: false
  comment_severity_threshold: HIGH
  max_review_comments: 5
  pull_request_opened:
    help: false
    summary: false
    code_review: true
ignore_patterns:
  - "bin/*"
  - "lib/*"
  - "tests/*"
